# Generated by Django 4.0.4 on 2022-05-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braintree_id',
        ),
    ]
